# This is a basic workflow to help you get started with Actions

name: ubuntu-latest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: submodules
        run: |
          git submodule init
          git submodule update
    
      - name: setup
        run: |
          mkdir build       
          sudo apt install gcc-10 gcc-10-base gcc-10-doc g++-10
          sudo apt install libstdc++-10-dev libstdc++-10-doc
        
      - name: conan
        working-directory: ./build
        run: |
          pip install conan
          conan create ../lcm-recipe/ -o lcm:shared=True
          conan install .. --build

      - name: build
        working-directory: ./build
        run: | 
          cmake ..
          make
          
      - name: run
        working-directory: ./build
        run: timeout 5 bin/walter
